site:
  title: Training
  url: http://training.rezaulhasan.me
  start_page: java::index.adoc
  keys:
    google_analytics: 'UA-164685388-1'
content:
  sources:
    - url: .
      branches: HEAD
      start_path: docs
asciidoc:
  attributes:
    hide-uri-scheme: ''
    table-caption: ~
    page-toclevels: '3'
    tabs: tabs
  extensions:
    - ./lib/tabs-block.js
ui:
  bundle:
    #url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    url: https://github.com/couchbase/docs-ui/releases/download/v246/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui
output:
  dir: ./public
  clean: true
  destinations:
    - provider: archive
      path: ./public/master.zip
    - provider: fs
      path: ./
