= IntelliJ IDEA
:description: Introduction to IDE - IntelliJ IDEA. \
Most used keymaps | Useful Plugins
:keywords: java, oop, programming, ide, intellij
:experimental:

[abstract]
IntelliJ IDEA is one of the most popular IDE among java developers.
Ultimate and Community both editions are available for IntelliJ IDEA.
In this article developers will find some useful plugins to boost their development experience as well as most used keymaps to keep their hands mostly on the keyboard.

== Useful IntelliJ IDEA Plugins

- To generate boilerplate code (e.g. Getter, Setter and so on) during compile time
https://plugins.jetbrains.com/plugin/6317-lombok[Lombok, window=_blank] plugin is the best choice for the developers.
It is very easy to use due to its annotation based code generation.
- https://plugins.jetbrains.com/plugin/7391-asciidoc[AsciiDoc, window=_blank] plugin brings Asciidoc supports for the developer.
It helps to write the technical documentation easily on the same IDE they have used for the development.
- https://plugins.jetbrains.com/plugin/11058-extra-icons[Extra Icons, window=_blank] plugin helps to visually recognize different file formats almost instantly by their icons.
- If you are struggling to find opening and closing brackets in your code, https://plugins.jetbrains.com/plugin/10080-rainbow-brackets[Rainbow Brackets, window=_blank] plugin may help you.
It helps developers to find brackets through rainbow coloring.
- https://plugins.jetbrains.com/plugin/7275-codeglance[CodeGlance, window=_blank] plugin is a code mini map.
It helps to navigate fast across the editor window.

== Keymaps

[TIP]
====
.Keymap learning and presentation plugins for IntelliJ IDEA
- https://plugins.jetbrains.com/plugin/9792-key-promoter-x/versions[Key Promoter X] plugin shows a popup notification with the corresponding keyboard shortcut whenever a command executed using the mouse.
It also shows most used keymap statistics.

- https://plugins.jetbrains.com/plugin/7345-presentation-assistant[Presentation Assistant] plugin shows a popup with the corresponding description whenever a keymap pressed.
It can be very useful during presentation, screencast.

Both plugin can be used together for learning shortcuts.
====

NOTE: https://resources.jetbrains.com/storage/products/intellij-idea/docs/IntelliJIDEA_ReferenceCard.pdf[Download] the default keymap reference card by *Jetbrains*.
This keymap card is also available inside your IDE under menu:Help[Keymap Reference].

include::intellij-idea-keymap.adoc[]

== Additional Resources

=== Watch

* Pluralsight - https://app.pluralsight.com/library/courses/intellij-ce-getting-started/[Getting Started with IntelliJ CE, window="_blank"] by David Starr.
** Duration *2h 47m*.
** Released *1 Sep 2017*.

=== Read

* https://www.jetbrains.com/help/idea/getting-started.html[IntelliJ IDEA Getting started, window="_blank"]
* https://www.jetbrains.com/help/idea/mastering-keyboard-shortcuts.html[IntelliJ IDEA keyboard shortcuts﻿, window="_blank"]

